---
version: "3"
silent: true
output: prefixed
vars:
  black: \033[:0;30m
  red: \033[:0;31m
  green: \033[:0;32m
  orange: \033[:0;33m
  blue: \033[:0;34m
  purple: \033[:0;35m
  cyan: \033[:0;36m
  light_gray: \033[:0;37m
  dark_gray: \033[:1;30m
  light_red: \033[:1;31m
  light_green: \033[:1;32m
  yellow: \033[:1;33m
  light_blue: \033[:1;34m
  light_purple: \033[:1;35m
  light_cyan: \033[:1;36m
  white: \033[:1;37m
  nocolor: \u001b[0m
  reversed: \u001b[7m
  TODAY: '{{ now | date "2006-01-02T15:04:05-07:00" }}'

tasks:
  default:
    cmds:
      - task: list
  list:
    desc: list tasks
    cmds:
      - task --list
  vars:
    desc: variable output
    cmds:
      - |
        echo -e "{{.light_gray}}=== ℹ {{ .reversed }} Variable Info from Task {{ .nocolor }} === "
      # echo -e "{{.light_gray}}ARTIFACT_DIRECTORY          {{.nocolor}}: {{ .orange}}{{ .ARTIFACT_DIRECTORY }} {{ .nocolor }}"
  init:vmware:
    desc: setup tooling for project and download dependencies
    cmds:
      - |
        vagrant plugin install vagrant-vmware-desktop
  windows10:up:
    desc: Start up windows 10 vagrant box
    dir: windows10
    silent: false
    cmds:
      - |
        vagrant up
  windows10:halt:
    desc: Shutdown windows 10 vagrant box
    dir: windows10
    silent: false
    cmds:
      - |
        vagrant halt
  windows10:provision:
    desc: run the Windows10 provisioning commands
    dir: windows10
    silent: false
    cmds:
      - |
        vagrant provision
  ubuntu-kinetic:up:
    desc: Start up vagrant box
    dir: ubuntu-kinetic
    silent: false
    cmds:
      - |
        vagrant up
  ubuntu-kinetic:halt:
    desc: Shutdown vagrant box
    dir: ubuntu-kinetic
    silent: false
    cmds:
      - |
        vagrant halt
  ubuntu-kinetic:provision:
    desc: run the Ubuntu-kinetic provisioning commands
    dir: ubuntu-kinetic
    silent: false
    cmds:
      - |
        vagrant provision
